version: '3.6'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    volumes:
      - .:/usr/src/app/
    command: gunicorn --bind 0.0.0.0:5000 app:app --log-level=debug
    # command: gunicorn --bind 0.0.0.0:5000 wsgi:application --log-level=debug
    ports:
      - 5000:5000
    env_file:
      - ./.env.docker
    depends_on:
      - pgdb
      - redis
  
  seeder:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: seeder
    #command: flask db upgrade && seed run
    command: /bin/sh -c "./migrate.sh"
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.docker
    depends_on:
      - web
      - pgdb

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: worker
    command: celery --app make.celery_app worker --concurrency=4 -l INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.docker
    depends_on:
      - web
      - pgdb
      - redis
  
  beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A make.celery_app beat --loglevel=INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.docker
    depends_on:
      - web
      - pgdb
      - redis

  flower:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery --app make.celery_app flower --port=5555  -l INFO -E
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis
      - beat
      - worker

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mss_pg_db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: cache_redis
    # command: redis-server --requirepass Redis2019!
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - dataredis:/var/lib/redis/data


  # rabbitmq:
  #   image: rabbitmq:management
  #   container_name: 'rabbitmq'
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   ports:
  #     - 5672:5672
  #     - 15672:15672

volumes:
  services_web:
  pgdata:
  dataredis: