version: '3.6'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
    #  - './services/web:/usr/src/app'
    # command: gunicorn --bind 0.0.0.0:5000 app:app
    # command: gunicorn --bind 0.0.0.0:5000 wsgi:application
    ports:
      - 5000:5000
    env_file:
      - ./.env
    # environment:
    #   - FLASK_ENV=development
    #   - FLASK_APP=app.py
    #   - FLASK_DEBUG=1
    #   - APP_SETTINGS=config.DevelopmentConfig
    #   - DATABASE_URL=postgresql://postgres:postgres@localhost/mss_pg_db
    #   - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
    #   - SECRET_KEY=my_precious
    depends_on:
      - pgdb
      - redis
  
  # monitor:
  #   image: dev3_web
  #   ports:
  #     - 5555:5555
  #   command:  flower -A celery_worker.celery --port=5555 --broker=redis://redis:6379/0
  #   depends_on:
  #     - web
  #     - redis

  # celery:
  #   build: .
  #   container_name: celery
  #   command: celery -A core worker -l info
  #   restart: always
  #   volumes:
  #     - .:/usr/src/app/
  #   environment:
  #     - CELERY_BROKER=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   links:
  #     - redis:redis
  #   depends_on:
  #     - web
  #     - django
  #     - rabbitmq
  #     - redis

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mss_pg_db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: cache_redis
    # image: 'redis:5-alpine'
    # command: redis-server --requirepass Redis2019!
    command: redis-server
    ports:
      - "6380:6379"
    volumes:
      - dataredis:/var/lib/redis/data

  # redis:
  #   image: redis:5.0.3-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'

  # rabbitmq:
  #   image: rabbitmq:management
  #   container_name: 'rabbitmq'
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   ports:
  #     - 5672:5672
  #     - 15672:15672

volumes:
  pgdata:
  dataredis: