"""add colunm.

Revision ID: 40f47b8300c8
Revises: 97e5128a8ecb
Create Date: 2023-12-08 09:52:53.822654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f47b8300c8'
down_revision = '97e5128a8ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_types', schema=None) as batch_op:
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
