"""Initial bootstrap.

Revision ID: 97e5128a8ecb
Revises:
Create Date: 2023-12-05 20:58:08.125656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e5128a8ecb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('type_name', sa.String(length=128), nullable=True),
    sa.Column('disable', sa.Boolean(), nullable=True),
    sa.Column('globals', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_types')
    # ### end Alembic commands ###
